name: Kingdoms
main: org.edenmc.kingdoms.Kingdoms
version: 1.0.0
depend: []
website: edenmc.org
author: fLuK3_
commands:
  items:
    aliases: i
    permission: items.*
  gold:
    permission: gold.*
    aliases: bal
  kingdom:
    description: Kingdom command prefix
    aliases: k
  chunk:
    description: Chunk command prefix
    aliases: c
  accept:
    description: Accept invitation
  deny:
    description: Decline invitation